### ISSUE TITLE
Jupyter nbextensions does not work on jupyter-notebook 6.0.3

### ISSUE THREAD

**Issue by Jgleizal** [Jupyter-contrib/jupyter_nbextensions_configurator#117]
Hello, everybody!
I tried to install jupyter_nbextensions_configurator but it doesn't work on jupyter-notebook 6.0.3.
Is there an update planned? 
What is the problem? Maybe I can contribute...

Here's the error displayed:

`(base) c:\Packages Python>conda install jupyter_nbextensions_configurator-0.4.1-py37_0.tar.bz2

Downloading and Extracting Packages
############################################################################################################### | 100%
WARNING conda.core.prefix_data:_load_single_record(186): Ignoring malformed prefix record at: C:\Users\user\Anaconda\conda-meta\graphviz.json
Preparing transaction: done
Verifying transaction: done
Executing transaction: | b'Traceback (most recent call last):\n  File "C:\\Users\\user\\Anaconda\\Scripts\\jupyter-nbextensions_configurator-script.py", line 6, in <module>\n    from jupyter_nbextensions_configurator.application import main\n  File "C:\\Users\\user\\Anaconda\\lib\\site-packages\\jupyter_nbextensions_configurator\\application.py", line 12, in <module>\n    from jupyter_contrib_core.notebook_compat import nbextensions, serverextensions\nModuleNotFoundError: No module named \'jupyter_contrib_core\'\n'
done
ERROR conda.core.link:_execute(700): An error occurred while installing package '<unknown>::jupyter_nbextensions_configurator-0.4.1-py37_0'.
Rolling back transaction: done

LinkError: post-link script failed for package <unknown>::jupyter_nbextensions_configurator-0.4.1-py37_0
location of failed script: C:\Users\user\Anaconda\Scripts\.jupyter_nbextensions_configurator-post-link.bat
==> script messages <==
Traceback (most recent call last):
  File "C:\Users\user\Anaconda\Scripts\jupyter-nbextensions_configurator-script.py", line 6, in <module>
    from jupyter_nbextensions_configurator.application import main
  File "C:\Users\user\Anaconda\lib\site-packages\jupyter_nbextensions_configurator\application.py", line 12, in <module>
    from jupyter_contrib_core.notebook_compat import nbextensions, serverextensions
ModuleNotFoundError: No module named 'jupyter_contrib_core'

==> script output <==
stdout:
stderr:
return code: 1

()`

**Comment by cems2** [comment]
I had same problem.  I solved it by downgrading the notebook version 
`pip install notebook==6.1.5`
This appears to be related to a missing mathjax library in the new version of notebook
discussed here
https://discourse.jupyter.org/t/the-static-notebook-js-mathjaxutils-js-is-missing/7303
