### ISSUE TITLE
`jupyter contrib nbextension install --user` not working in Tensorflow 2.3 docker build with Ubuntu 18.04

### ISSUE THREAD

**Issue by wee-analyze** [Jupyter-contrib/jupyter_nbextensions_configurator#124]
Hi,

Operating system: Ubuntu 18.04 

I made a Dockerfile that pulls a jupyter notebook from Tensorflow and tried to add the jupyter notebook extensions but I'm getting errors and it won't make the image. I've used them before and didn't have a problem but don't know if I did something different this time around. It seems like the problem specifically happens with `jupyter contrib nbextension install --user`

The error I'm getting is 
```
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-contrib", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 662, in launch_instance
    app = cls.instance(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jupyter_contrib_core/application.py", line 27, in __init__
    self._refresh_subcommands()
  File "/usr/local/lib/python3.6/dist-packages/jupyter_contrib_core/application.py", line 43, in _refresh_subcommands
    get_subcommands_dict = entrypoint.load()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (nbformat 4.4.0 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('nbformat>=5.0'), {'nbclient'})
The command '/bin/bash -c pip install --upgrade pip 	&& pip install jupyter_contrib_nbextensions 	&& jupyter contrib nbextension install --user' returned a non-zero code: 1
```

This is the Dockerfile I use
```
FROM tensorflow/tensorflow:2.3.1-gpu-jupyter

RUN pip install --upgrade pip \
	&& pip install jupyter_contrib_nbextensions \
	&& jupyter contrib nbextension install --user \
	&& pip install jupyter_nbextensions_configurator \
	&& jupyter nbextensions_configurator enable --user \
	&& jupyter nbextension enable code_prettify/autopep8 \
	&& jupyter nbextension enable codefolding/main
```

Any ideas on how I can get this to work?

**Comment by rpytel1** [comment]
Hi, 

A similar problem is on tensorflow/tensorflow:2.4.0-gpu-jupyter when you install jupyter_contrib_nbextensions via pip:
 
`pip install jupyter_contrib_nbextensions`

and when you run it via: 

```
jupyter contrib nbextension install --user
```

Any update on how to fix that without downgrading Jupyter?
