### ISSUE TITLE
jupyter_nbextensions_configurator not installing correctly

### ISSUE THREAD

**Issue by rejogc** [Jupyter-contrib/jupyter_nbextensions_configurator#172]
I just tried to install this with pip. Here's my pip show results:

Name: jupyter-nbextensions-configurator
Version: 0.6.3
Summary: jupyter serverextension providing configuration interfaces for nbextensions.
Home-page: https://github.com/jupyter-contrib/jupyter_nbextensions_configurator
Author: jcb91, jupyter-contrib developers
Author-email: [joshuacookebarnes@gmail.com](mailto:joshuacookebarnes@gmail.com)
License: BSD 3-clause
Location: /home/rejogc/.local/lib/python3.10/site-packages
Requires: jupyter-contrib-core, jupyter-core, notebook, pyyaml, tornado, traitlets
Required-by: jupyter-contrib-nbextensions

when i start jupiter like this 'jupyter notebook', i get this error message in the stream of messages during startup:

[[W 2024-02-28 16:31:08.015 ServerApp] jupyter_nbextensions_configurator | error adding extension (enabled: True): The module 'jupyter_nbextensions_configurator' could not be found (No module named 'notebook.base'). Are you sure the extension is installed?
    Traceback (most recent call last):
      File "/home/rejogc/.local/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 322, in add_extension
        extpkg = ExtensionPackage(name=extension_name, enabled=enabled)
      File "/home/rejogc/.local/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 186, in __init__
        self._load_metadata()
      File "/home/rejogc/.local/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 201, in _load_metadata
        raise ExtensionModuleNotFound(msg) from None
    jupyter_server.extension.utils.ExtensionModuleNotFound: The module 'jupyter_nbextensions_configurator' could not be found (No module named 'notebook.base'). Are you sure the extension is installed?

Looks like something's missing from the distribution

**Comment by MissingTwins** [comment]
Same problem here

```
D:\work\whisper>jupyter nbextensions_configurator enable --user
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\chelsea\AppData\Local\Programs\Python\Python311\Scripts\jupyter-nbextensions_configurator.EXE\__main__.py"
, line 4, in <module>
  File "C:\Users\chelsea\AppData\Local\Programs\Python\Python311\Lib\site-packages\jupyter_nbextensions_configurator\__init
__.py", line 18, in <module>
    from notebook.base.handlers import APIHandler, IPythonHandler
ModuleNotFoundError: No module named 'notebook.base'

```

**Comment by GLOFonseca** [comment]
Same problem:

```
C:\Users\Fonseca>jupyter nbextensions_configurator enable --user  # can be skipped for notebook >=5.3
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Fonseca\AppData\Local\Programs\Python\Python312\Scripts\jupyter-nbextensions_configurator.EXE\__main__.py", line 4, in <module>
  File "C:\Users\Fonseca\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_nbextensions_configurator\__init__.py", line 18, in <module>
    from notebook.base.handlers import APIHandler, IPythonHandler
ModuleNotFoundError: No module named 'notebook.base'
```

pip version: 24.0
jupyter version:
```
C:\Users\Fonseca>jupyter --version
Selected Jupyter core packages...
IPython          : 8.23.0
ipykernel        : 6.29.4
ipywidgets       : 8.1.2
jupyter_client   : 8.6.1
jupyter_core     : 5.7.2
jupyter_server   : 2.13.0
jupyterlab       : 4.1.6
nbclient         : 0.10.0
nbconvert        : 7.16.3
nbformat         : 5.10.4
notebook         : 7.1.2
qtconsole        : 5.5.1
traitlets        : 5.14.2
```

**Comment by cif2cif** [comment]
Same problem.
>jupyter nbextensions_configurator enable --user
Traceback (most recent call last):
  File "/home/cif/anaconda3/bin/jupyter-nbextensions_configurator", line 5, in <module>
    from jupyter_nbextensions_configurator.application import main
  File "/home/cif/anaconda3/lib/python3.11/site-packages/jupyter_nbextensions_configurator/__init__.py", line 18, in <module>
    from notebook.base.handlers import APIHandler, IPythonHandler
ModuleNotFoundError: No module named 'notebook.base'

>jupyter --version
Selected Jupyter core packages...
IPython          : 8.23.0
ipykernel        : 6.29.4
ipywidgets       : 7.6.5
jupyter_client   : 8.6.1
jupyter_core     : 5.7.2
jupyter_server   : 2.14.0
jupyterlab       : 4.1.6
nbclient         : 0.10.0
nbconvert        : 7.16.3
nbformat         : 5.10.4
notebook         : 7.1.2
qtconsole        : 5.5.1
traitlets        : 5.14.2

**Comment by stuaxocabinetoffice** [comment]
I can't test this right now, it would be good to work out which version of jupyter the change happened in, if anyone has time to try earlier with an earlier version of it, this might narrow it down.

**Comment by jph00** [comment]
It looks like there might be a fix for this here:

https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/commit/a600cef9222ca0c61a6912eb29d8fa0323409705

@RRosio does this project need a release pushed to get this fix?

**Comment by RRosio** [comment]
Hi everyone, I was able to cut a release from with the latest updates that had been merged! If you would like to try it and report any further issues, you can find it here: https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/releases/tag/0.6.4

cc @rejogc @MissingTwins @GLOFonseca @jph00 @cif2cif
