### ISSUE TITLE
json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by billchenxi** [Jupyter-contrib/jupyter_nbextensions_configurator#36]
Hi there,
I installed jupyter extension for python 3.6 (root) and python 3.5 (envir), it was working before, but right now it stop working and I tried to reinstall the jupyter_nbextensions_configurator, and enable it, I got errors:

```
$ jupyter nbextensions_configurator enable --user
Enabling: jupyter_nbextensions_configurator
- Writing config: /Users/Bill/.jupyter
    - Validating...
      jupyter_nbextensions_configurator  OK
Enabling notebook nbextension nbextensions_configurator/config_menu/main...
Traceback (most recent call last):
  File "/Users/Bill/miniconda3/bin/jupyter-nbextensions_configurator", line 11, in <module>
    sys.exit(main())
  File "/Users/Bill/miniconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/Bill/miniconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/Bill/miniconda3/lib/python3.6/site-packages/jupyter_nbextensions_configurator/application.py", line 117, in start
    super(JupyterNbextensionsConfiguratorApp, self).start()
  File "/Users/Bill/miniconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/Users/Bill/miniconda3/lib/python3.6/site-packages/jupyter_nbextensions_configurator/application.py", line 77, in start
    user=self.user, sys_prefix=self.sys_prefix)
  File "/Users/Bill/miniconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 345, in _set_nbextension_state
    cm.update(section, {"load_extensions": {require: state}})
  File "/Users/Bill/miniconda3/lib/python3.6/site-packages/traitlets/config/manager.py", line 85, in update
    data = self.get(section_name)
  File "/Users/Bill/miniconda3/lib/python3.6/site-packages/traitlets/config/manager.py", line 63, in get
    return json.load(f)
  File "/Users/Bill/miniconda3/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/Users/Bill/miniconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/Bill/miniconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/Bill/miniconda3/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 58 column 3 (char 1820)`
```

Would you mind to help me to debug?

Thanks,
Bill

**Comment by jcb91** [comment]
Hi Dill, it looks as though a json config file has been edited incorrectly somehow. I'd guess manually, but I think someone else had this problem before without manual editing, so perhaps not. At any rate, it seems like you have a syntax error at line 58 column 3 in the config file 

    /Users/Bill/.jupyter/jupyter_notebook_config.json

specifically, an expected comma, which the parser doesn't find. If you need further help, perhaps you could post the file contents (assuming it doesn't contain sensitive details)?

**Comment by jcb91** [comment]
blegh, sorry, Bill!

**Comment by jcb91** [comment]
Did you make any progress on this @billchenxi?

**Comment by jcb91** [comment]
Closing this as hopefully fixed, in absence of further details.
