### ISSUE TITLE
Problem enabling nbextensions

### ISSUE THREAD

**Issue by ppau1** [Jupyter-contrib/jupyter_nbextensions_configurator#60]
I just installed nbextensions using `pip install jupyter_contrib_nbextensions
` and `upyter contrib nbextension install --user`. 

When I try to enable an extension I get the foloowing error message:

```bash
▶ jupyter nbextension enable toc2/main
Enabling notebook extension toc2/main...
Traceback (most recent call last):
  File "/home/pauperei/.conda/envs/py36/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/notebook/nbextensions.py", line 900, in start
    super(NBExtensionApp, self).start()
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/notebook/nbextensions.py", line 810, in start
    self.toggle_nbextension(self.extra_args[0])
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/notebook/nbextensions.py", line 800, in toggle_nbextension
    logger=self.log)
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/notebook/nbextensions.py", line 393, in enable_nbextension
    logger=logger)
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/notebook/nbextensions.py", line 331, in _set_nbextension_state
    cm.update(section, {"load_extensions": {require: state}})
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/traitlets/config/manager.py", line 85, in update
    data = self.get(section_name)
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/traitlets/config/manager.py", line 63, in get
    return json.load(f)
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5 column 3 (char 133)
```

I'm using Python 3.6 on a Linux machine.

**Comment by jcb91** [comment]
> `json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5 column 3 (char 133)`

This line means you have a corrupted json config file somewhere. To find out which file, you can try the following python snippet:

```python
import glob
import os
import json

from jupyter_core.paths import jupyter_config_path

for d in jupyter_config_path():
    for p in glob.glob(os.path.join(d, 'nbconfig', '*.json')):
        try:
            with open(p, 'r') as f:
                json.load(f)
            print('{0} is OK.'.format(p))
        except json.decoder.JSONDecodeError as err:
            print('{0} has a problem:'.format(p), err)
```

You can edit this file to fix the syntax error, or post the contents here if you'd like further help. However, depending on the root cause, this may happen again. The most likely causes of this are:

  * you edited a json config file by hand, and made a mistake (not super likely, but possible). If this is the case, it shouldn't happen again unless you make more manual edits :stuck_out_tongue_winking_eye: 
  * (more likely) you got bitten by a bug caused by a combination of jupyter notebook's config editing and a serverextension like [jupyter-notebook-gist](https://github.com/mozilla/jupyter-notebook-gist). In this case, the problem can reoccur every time the notebook is run. See below for details.

For the second case, see https://github.com/mozilla/jupyter-notebook-gist/issues/56 for a serverextension bug causing this, https://github.com/jupyter/notebook/pull/3305 for the fix from notebook, and https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1211 for discussion of this problem. The most likely fixes are to disable or upgrade jupyter-notebook-gist, or possibly notebook

**Comment by ppau1** [comment]
@jcb91 this is great! Your script returned 

```
/local/home/pauperei/.jupyter/nbconfig/notebook.json has a problem: Expecting property name enclosed in double quotes: line 5 column 3 (char 133)
/local/home/pauperei/.jupyter/nbconfig/common.json is OK.
/local/home/pauperei/.jupyter/nbconfig/tree.json is OK.
```

The file at `/local/home/pauperei/.jupyter/nbconfig/notebook.json` looks like this

```
{
  "load_extensions": {
    "nbextensions_configurator/config_menu/main": true,
    "contrib_nbextensions_help_item/main": true, 
  }
}
```

But I'm not sure what the problem is. Also, I have no recollection of ever editing this file.
Thanks!

**Comment by jcb91** [comment]
> I'm not sure what the problem is

The problem here is the comma after the second entry. JSON is strict about not allowing trailing commas in lists or objects (whereas python & JavaScript will tolerate  trailing commas at the end of list/array or dict/object literals).

The contents should be

```json
{
  "load_extensions": {
    "nbextensions_configurator/config_menu/main": true,
    "contrib_nbextensions_help_item/main": true
  }
}
```

> Also, I have no recollection of ever editing this file

You may not have, it may have been done by a script. In general, scripts *should* leave properly-formatted json, but sometimes things go wrong, I guess.

**Comment by ppau1** [comment]
This solves the problem. Thank you, you've been awesome!

**Comment by dhiren-hamal** [comment]
> * 
> * (more likely) you got bitten by a bug caused by a combination of jupyter notebook's config editin

When I tried to install the jupyter_contrib_nbextensions my jupyter got messed up, I find out the problem @jcb91 comments and came to know that .jupyter/nbconfig/notebook.json was empty

Thank you @jcb91
