### ISSUE TITLE
Error loading server extension ==py

### ISSUE THREAD

**Issue by JohnOwnbyHibner** [Jupyter-contrib/jupyter_nbextensions_configurator#99]
Hi,
I've run into this issue and can't seem to resolve it. I've uninstalled/reinstalled the environment, uninstalled/reinstalled anaconda. it was working fine a couple of days ago. Now I'm having issues importing libraries into notebooks.

[I 16:57:39.984 LabApp] [nb_conda_kernels] enabled, 4 kernels found
[W 16:57:40.858 LabApp] Permission to listen on port 8888 denied
[W 16:57:40.867 LabApp] **Error loading server extension ==py**
Traceback (most recent call last):
File "F:\Anaconda\envs\Development_3_7\lib\site-packages\notebook\notebookapp.py", line 1572, in init_server_extensions
mod = importlib.import_module(modulename)
File "F:\Anaconda\envs\Development_3_7\lib\importlib\__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1006, in _gcd_import
File "", line 983, in _find_and_load
File "", line 965, in _find_and_load_unlocked
**ModuleNotFoundError: No module named '==py'**
[I 16:57:40.884 LabApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 16:57:40.888 LabApp] JupyterLab extension loaded from F:\Anaconda\envs\Development_3_7\lib\site-packages\jupyterlab
[I 16:57:40.888 LabApp] JupyterLab application directory is F:\Anaconda\envs\Development_3_7\share\jupyter\lab
[I 16:57:40.894 LabApp] [nb_conda] enabled
[W 16:57:40.894 LabApp] JupyterLab server extension not enabled, manually loading...
[I 16:57:40.896 LabApp] JupyterLab extension loaded from F:\Anaconda\envs\Development_3_7\lib\site-packages\jupyterlab
[I 16:57:40.896 LabApp] JupyterLab application directory is F:\Anaconda\envs\Development_3_7\share\jupyter\lab
[I 16:57:40.897 LabApp] Serving notebooks from local directory: f:\
[I 16:57:40.897 LabApp] The Jupyter Notebook is running at:
[I 16:57:40.897 LabApp] http://localhost:8889/?token=<removed by poster>
[I 16:57:40.897 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:57:40.942 LabApp]

**Comment by JohnOwnbyHibner** [comment]
I have uninstalled the Jupyter Lab from all Anaconda environments, rebooted, and reinstalled Jupyter Lab. This has resolved the issue
